# Generated by Django 5.2.4 on 2025-07-11 10:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=20, unique=True, verbose_name='Banka Kodu')),
                ('ad', models.CharField(max_length=100, verbose_name='Banka Adı')),
                ('sube', models.CharField(blank=True, max_length=100, verbose_name='Şube')),
                ('hesap_no', models.CharField(max_length=30, verbose_name='Hesap No')),
                ('iban', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator(message='Geçerli bir IBAN giriniz', regex='^TR[0-9]{24}$')], verbose_name='IBAN')),
                ('doviz', models.CharField(choices=[('TRY', 'Türk Lirası'), ('USD', 'Amerikan Doları'), ('EUR', 'Euro'), ('GBP', 'İngiliz Sterlini')], default='TRY', max_length=3, verbose_name='Döviz')),
                ('bakiye', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Bakiye')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Banka',
                'verbose_name_plural': 'Bankalar',
                'db_table': 'bankalar',
                'ordering': ['kod'],
            },
        ),
        migrations.CreateModel(
            name='CariKart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=20, unique=True, verbose_name='Cari Kod')),
                ('unvan', models.CharField(max_length=200, verbose_name='Ünvan')),
                ('tip', models.CharField(choices=[('musteri', 'Müşteri'), ('tedarikci', 'Tedarikçi'), ('her_ikisi', 'Müşteri ve Tedarikçi')], default='musteri', max_length=10, verbose_name='Cari Tipi')),
                ('vergi_no', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Vergi no 10 veya 11 haneli olmalıdır', regex='^[0-9]{10,11}$')], verbose_name='Vergi No')),
                ('vergi_dairesi', models.CharField(blank=True, max_length=100, verbose_name='Vergi Dairesi')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('adres', models.TextField(blank=True, verbose_name='Adres')),
                ('sehir', models.CharField(blank=True, max_length=50, verbose_name='Şehir')),
                ('bakiye', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Bakiye')),
                ('risk_limiti', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Risk Limiti')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Cari Kart',
                'verbose_name_plural': 'Cari Kartlar',
                'db_table': 'cari_kartlar',
                'ordering': ['kod'],
            },
        ),
        migrations.CreateModel(
            name='Kasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=20, unique=True, verbose_name='Kasa Kodu')),
                ('ad', models.CharField(max_length=100, verbose_name='Kasa Adı')),
                ('doviz', models.CharField(choices=[('TRY', 'Türk Lirası'), ('USD', 'Amerikan Doları'), ('EUR', 'Euro'), ('GBP', 'İngiliz Sterlini')], default='TRY', max_length=3, verbose_name='Döviz')),
                ('bakiye', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Bakiye')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Kasa',
                'verbose_name_plural': 'Kasalar',
                'db_table': 'kasalar',
                'ordering': ['kod'],
            },
        ),
        migrations.CreateModel(
            name='StokKart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=30, unique=True, verbose_name='Stok Kodu')),
                ('ad', models.CharField(max_length=200, verbose_name='Stok Adı')),
                ('barkod', models.CharField(blank=True, max_length=20, verbose_name='Barkod')),
                ('birim', models.CharField(choices=[('ADET', 'Adet'), ('KG', 'Kilogram'), ('METRE', 'Metre'), ('LITRE', 'Litre'), ('PAKET', 'Paket'), ('KOLI', 'Koli')], default='ADET', max_length=10, verbose_name='Birim')),
                ('miktar', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Mevcut Miktar')),
                ('kritik_stok', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Kritik Stok Seviyesi')),
                ('alis_fiyati', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Alış Fiyatı')),
                ('satis_fiyati', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Satış Fiyatı')),
                ('kdv_orani', models.IntegerField(default=20, verbose_name='KDV Oranı %')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
            ],
            options={
                'verbose_name': 'Stok Kart',
                'verbose_name_plural': 'Stok Kartlar',
                'db_table': 'stok_kartlar',
                'ordering': ['kod'],
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatura_no', models.CharField(max_length=20, unique=True, verbose_name='Fatura No')),
                ('tarih', models.DateField(default=django.utils.timezone.now, verbose_name='Fatura Tarihi')),
                ('tip', models.CharField(choices=[('alis', 'Alış Faturası'), ('satis', 'Satış Faturası'), ('iade_alis', 'Alış İade Faturası'), ('iade_satis', 'Satış İade Faturası')], max_length=20, verbose_name='Fatura Tipi')),
                ('ara_toplam', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ara Toplam')),
                ('kdv_tutari', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='KDV Tutarı')),
                ('genel_toplam', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Genel Toplam')),
                ('vade_tarihi', models.DateField(blank=True, null=True, verbose_name='Vade Tarihi')),
                ('odendi', models.BooleanField(default=False, verbose_name='Ödendi')),
                ('iptal', models.BooleanField(default=False, verbose_name='İptal')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('cari', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturalar', to='muhasebe.carikart', verbose_name='Cari')),
                ('olusturan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturalar',
                'db_table': 'faturalar',
                'ordering': ['-tarih', '-fatura_no'],
            },
        ),
        migrations.CreateModel(
            name='KasaHareket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tarih')),
                ('tip', models.CharField(choices=[('giris', 'Giriş'), ('cikis', 'Çıkış')], max_length=10, verbose_name='Hareket Tipi')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Tutar')),
                ('aciklama', models.CharField(max_length=200, verbose_name='Açıklama')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('cari', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kasa_hareketleri', to='muhasebe.carikart', verbose_name='Cari')),
                ('fatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kasa_hareketleri', to='muhasebe.fatura', verbose_name='Fatura')),
                ('kasa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hareketler', to='muhasebe.kasa', verbose_name='Kasa')),
                ('olusturan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Kasa Hareketi',
                'verbose_name_plural': 'Kasa Hareketleri',
                'db_table': 'kasa_hareketleri',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='FaturaKalem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Miktar')),
                ('birim_fiyat', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Birim Fiyat')),
                ('kdv_orani', models.IntegerField(default=20, verbose_name='KDV %')),
                ('tutar', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tutar')),
                ('kdv_tutari', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='KDV Tutarı')),
                ('toplam_tutar', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Toplam Tutar')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='muhasebe.fatura', verbose_name='Fatura')),
                ('stok', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='muhasebe.stokkart', verbose_name='Stok')),
            ],
            options={
                'verbose_name': 'Fatura Kalemi',
                'verbose_name_plural': 'Fatura Kalemleri',
                'db_table': 'fatura_kalemleri',
            },
        ),
    ]
