# Generated by Django 5.2.4 on 2025-07-11 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Il',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, unique=True, verbose_name='İl Adı')),
                ('plaka', models.IntegerField(unique=True, verbose_name='Plaka Kodu')),
            ],
            options={
                'verbose_name': 'İl',
                'verbose_name_plural': 'İller',
                'db_table': 'iller',
                'ordering': ['plaka'],
            },
        ),
        migrations.RemoveField(
            model_name='carikart',
            name='sehir',
        ),
        migrations.AddField(
            model_name='carikart',
            name='yetkili_adi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Yetkili Adı Soyadı'),
        ),
        migrations.AddField(
            model_name='carikart',
            name='yetkili_tel1',
            field=models.CharField(blank=True, max_length=20, verbose_name='Yetkili No 1'),
        ),
        migrations.AddField(
            model_name='carikart',
            name='yetkili_tel2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Yetkili No 2'),
        ),
        migrations.AddField(
            model_name='carikart',
            name='yetkili_tel3',
            field=models.CharField(blank=True, max_length=20, verbose_name='Yetkili No 3'),
        ),
        migrations.AlterField(
            model_name='carikart',
            name='kod',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Cari Kod'),
        ),
        migrations.CreateModel(
            name='CariGrup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=20, unique=True, verbose_name='Grup Kodu')),
                ('ad', models.CharField(max_length=100, verbose_name='Grup Adı')),
                ('seviye', models.IntegerField(default=1, verbose_name='Seviye')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('ust_grup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alt_gruplar', to='muhasebe.carigrup', verbose_name='Üst Grup')),
            ],
            options={
                'verbose_name': 'Cari Grup',
                'verbose_name_plural': 'Cari Gruplar',
                'db_table': 'cari_gruplar',
                'ordering': ['kod'],
            },
        ),
        migrations.AddField(
            model_name='carikart',
            name='grup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cariler', to='muhasebe.carigrup', verbose_name='Cari Grubu'),
        ),
        migrations.AddField(
            model_name='carikart',
            name='il',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muhasebe.il', verbose_name='İl'),
        ),
        migrations.CreateModel(
            name='Ilce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, verbose_name='İlçe Adı')),
                ('il', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilceler', to='muhasebe.il', verbose_name='İl')),
            ],
            options={
                'verbose_name': 'İlçe',
                'verbose_name_plural': 'İlçeler',
                'db_table': 'ilceler',
                'ordering': ['ad'],
                'unique_together': {('il', 'ad')},
            },
        ),
        migrations.AddField(
            model_name='carikart',
            name='ilce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muhasebe.ilce', verbose_name='İlçe'),
        ),
    ]
