# Generated by Django 5.2.4 on 2025-07-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0002_il_remove_carikart_sehir_carikart_yetkili_adi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carigrup',
            name='kod',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Grup Kodu'),
        ),
    ]
