# Generated by Django 5.2.4 on 2025-07-12 11:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0003_alter_carigrup_kod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carigrup',
            name='guncelleme_tarihi',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AddField(
            model_name='carigrup',
            name='olusturma_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 12, 11, 10, 35, 740850, tzinfo=datetime.timezone.utc), verbose_name='Oluşturma Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carigrup',
            name='silen_kullanici',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_silen', to=settings.AUTH_USER_MODEL, verbose_name='Silen Kullanıcı'),
        ),
        migrations.AddField(
            model_name='carigrup',
            name='silindi',
            field=models.BooleanField(default=False, verbose_name='Silindi'),
        ),
        migrations.AddField(
            model_name='carigrup',
            name='silinme_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi'),
        ),
        migrations.AddField(
            model_name='carikart',
            name='silen_kullanici',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_silen', to=settings.AUTH_USER_MODEL, verbose_name='Silen Kullanıcı'),
        ),
        migrations.AddField(
            model_name='carikart',
            name='silindi',
            field=models.BooleanField(default=False, verbose_name='Silindi'),
        ),
        migrations.AddField(
            model_name='carikart',
            name='silinme_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi'),
        ),
    ]
