# Generated by Django 5.2.4 on 2025-07-12 11:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0005_banka_guncelleme_tarihi_banka_olusturma_tarihi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carikart',
            name='tip',
        ),
        migrations.AddField(
            model_name='carikart',
            name='firma_tipi',
            field=models.CharField(choices=[('sahis', 'Şahıs Firması'), ('sirket', 'Şirket')], default='sahis', max_length=10, verbose_name='Firma Tipi'),
        ),
        migrations.AddField(
            model_name='carikart',
            name='sirket_unvani',
            field=models.CharField(blank=True, max_length=200, verbose_name='Şirket Ünvanı'),
        ),
        migrations.AddField(
            model_name='carikart',
            name='tc_kimlik',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='TC Kimlik No 11 haneli olmalıdır', regex='^[0-9]{11}$')], verbose_name='TC Kimlik No'),
        ),
        migrations.AlterField(
            model_name='carikart',
            name='adres',
            field=models.TextField(verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='carikart',
            name='grup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cariler', to='muhasebe.carigrup', verbose_name='Cari Grubu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carikart',
            name='il',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='muhasebe.il', verbose_name='İl'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carikart',
            name='ilce',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='muhasebe.ilce', verbose_name='İlçe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carikart',
            name='telefon',
            field=models.CharField(max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='carikart',
            name='yetkili_adi',
            field=models.CharField(max_length=100, verbose_name='Yetkili Adı Soyadı'),
        ),
    ]
