# Generated by Django 5.2.4 on 2025-07-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0006_remove_carikart_tip_carikart_firma_tipi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carikart',
            name='notlar',
            field=models.TextField(blank=True, verbose_name='Notlar'),
        ),
    ]
