# Generated by Django 5.2.4 on 2025-07-12 14:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0007_carikart_notlar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banka',
            name='doviz',
        ),
        migrations.RemoveField(
            model_name='kasa',
            name='doviz',
        ),
        migrations.CreateModel(
            name='ParaBirimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('silindi', models.BooleanField(default=False, verbose_name='Silindi')),
                ('silinme_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('kod', models.CharField(max_length=3, unique=True, verbose_name='Para Birimi Kodu')),
                ('ad', models.CharField(max_length=50, verbose_name='Para Birimi Adı')),
                ('sembol', models.CharField(max_length=5, verbose_name='Sembol')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('silen_kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_silen', to=settings.AUTH_USER_MODEL, verbose_name='Silen Kullanıcı')),
            ],
            options={
                'verbose_name': 'Para Birimi',
                'verbose_name_plural': 'Para Birimleri',
                'db_table': 'para_birimleri',
                'ordering': ['kod'],
            },
        ),
        migrations.AddField(
            model_name='banka',
            name='para_birimi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bankalar', to='muhasebe.parabirimi', verbose_name='Para Birimi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kasa',
            name='para_birimi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='kasalar', to='muhasebe.parabirimi', verbose_name='Para Birimi'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Pos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('silindi', models.BooleanField(default=False, verbose_name='Silindi')),
                ('silinme_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('kod', models.CharField(max_length=20, unique=True, verbose_name='POS Kodu')),
                ('ad', models.CharField(max_length=100, verbose_name='POS Adı')),
                ('komisyon_orani', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Komisyon Oranı %')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('banka', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='muhasebe.banka', verbose_name='Banka')),
                ('silen_kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_silen', to=settings.AUTH_USER_MODEL, verbose_name='Silen Kullanıcı')),
            ],
            options={
                'verbose_name': 'POS',
                'verbose_name_plural': 'POS Cihazları',
                'db_table': 'poslar',
                'ordering': ['kod'],
            },
        ),
        migrations.CreateModel(
            name='CariHareket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('silindi', models.BooleanField(default=False, verbose_name='Silindi')),
                ('silinme_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now, verbose_name='İşlem Tarihi')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Tutar')),
                ('hareket_yonu', models.CharField(choices=[('giris', 'Giriş'), ('cikis', 'Çıkış')], max_length=10, verbose_name='Hareket Yönü')),
                ('islem_tipi', models.CharField(choices=[('nakit', 'Nakit'), ('banka', 'Banka'), ('pos', 'POS'), ('diger', 'Diğer')], max_length=10, verbose_name='İşlem Tipi')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('banka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cari_hareketleri', to='muhasebe.banka', verbose_name='Banka')),
                ('cari', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hareketler', to='muhasebe.carikart', verbose_name='Cari')),
                ('kasa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cari_hareketleri', to='muhasebe.kasa', verbose_name='Kasa')),
                ('olusturan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('silen_kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_silen', to=settings.AUTH_USER_MODEL, verbose_name='Silen Kullanıcı')),
                ('para_birimi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='muhasebe.parabirimi', verbose_name='Para Birimi')),
                ('pos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cari_hareketleri', to='muhasebe.pos', verbose_name='POS')),
            ],
            options={
                'verbose_name': 'Cari Hareket',
                'verbose_name_plural': 'Cari Hareketler',
                'db_table': 'cari_hareketler',
                'ordering': ['-tarih', '-id'],
            },
        ),
    ]
