# Generated by Django 5.2.4 on 2025-07-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0008_remove_banka_doviz_remove_kasa_doviz_parabirimi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carihareket',
            name='doviz_kuru',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Döviz Kuru'),
        ),
        migrations.AddField(
            model_name='carihareket',
            name='tl_karsiligi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='TL Karşılığı'),
        ),
    ]
