# Generated by Django 5.2.4 on 2025-07-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0011_stokkart_para_birimi_alter_carihareket_islem_tipi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoksecenekdeger',
            name='varsayilan',
            field=models.BooleanField(default=False, verbose_name='Varsayılan'),
        ),
    ]
