# Generated by Django 5.2.4 on 2025-07-23 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0013_genelstoksecenek_genelstoksecenekdeger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StokGrup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('silindi', models.BooleanField(default=False, verbose_name='Silindi')),
                ('silinme_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('kod', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Grup Kodu')),
                ('ad', models.CharField(max_length=100, verbose_name='Grup Adı')),
                ('seviye', models.IntegerField(default=1, verbose_name='Seviye')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('silen_kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_silen', to=settings.AUTH_USER_MODEL, verbose_name='Silen Kullanıcı')),
                ('ust_grup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alt_gruplar', to='muhasebe.stokgrup', verbose_name='Üst Grup')),
            ],
            options={
                'verbose_name': 'Stok Grup',
                'verbose_name_plural': 'Stok Gruplar',
                'db_table': 'stok_gruplar',
                'ordering': ['kod'],
            },
        ),
        migrations.AddField(
            model_name='stokkart',
            name='grup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stoklar', to='muhasebe.stokgrup', verbose_name='Stok Grubu'),
        ),
    ]
