# Generated by Django 5.2.4 on 2025-08-06 11:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0014_stokgrup_stokkart_grup'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='aciklama',
            field=models.TextField(blank=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='iskonto_degeri',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='İskonto Değeri'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='iskonto_tipi',
            field=models.CharField(blank=True, choices=[('yuzde', 'Yüzde'), ('tutar', 'Sabit Tutar')], max_length=10, null=True, verbose_name='İskonto Tipi'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='iskonto_tutari',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='İskonto Tutarı'),
        ),
        migrations.AddField(
            model_name='faturakalem',
            name='indirim_aciklama',
            field=models.CharField(blank=True, max_length=200, verbose_name='İndirim Açıklama'),
        ),
        migrations.AddField(
            model_name='faturakalem',
            name='indirim_orani',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='İndirim %'),
        ),
        migrations.AddField(
            model_name='faturakalem',
            name='indirim_tutari',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='İndirim Tutarı'),
        ),
        migrations.AddField(
            model_name='faturakalem',
            name='secenek_fiyat_farki',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Seçenek Fiyat Farkı'),
        ),
        migrations.AddField(
            model_name='faturakalem',
            name='secenekler',
            field=models.JSONField(blank=True, default=dict, verbose_name='Seçenekler'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='tarih',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fatura Tarihi'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='tip',
            field=models.CharField(choices=[('satis', 'Satış Faturası'), ('alis', 'Alış Faturası')], max_length=20, verbose_name='Fatura Tipi'),
        ),
    ]
