# Generated by Django 5.2.4 on 2025-08-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0015_fatura_aciklama_fatura_iskonto_degeri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturakalem',
            name='kdv_durumu',
            field=models.CharField(choices=[('dahil', 'KDV Dahil'), ('haric', 'KDV Hariç')], default='dahil', max_length=10, verbose_name='KDV Durumu'),
        ),
    ]
