# Generated by Django 5.2.4 on 2025-07-12 11:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0004_carigrup_guncelleme_tarihi_carigrup_olusturma_tarihi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='banka',
            name='guncelleme_tarihi',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AddField(
            model_name='banka',
            name='olusturma_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 12, 11, 13, 0, 202197, tzinfo=datetime.timezone.utc), verbose_name='Oluşturma Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banka',
            name='silen_kullanici',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_silen', to=settings.AUTH_USER_MODEL, verbose_name='Silen Kullanıcı'),
        ),
        migrations.AddField(
            model_name='banka',
            name='silindi',
            field=models.BooleanField(default=False, verbose_name='Silindi'),
        ),
        migrations.AddField(
            model_name='banka',
            name='silinme_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='guncelleme_tarihi',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='silen_kullanici',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_silen', to=settings.AUTH_USER_MODEL, verbose_name='Silen Kullanıcı'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='silindi',
            field=models.BooleanField(default=False, verbose_name='Silindi'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='silinme_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi'),
        ),
        migrations.AddField(
            model_name='faturakalem',
            name='guncelleme_tarihi',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AddField(
            model_name='faturakalem',
            name='olusturma_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 12, 11, 13, 10, 624218, tzinfo=datetime.timezone.utc), verbose_name='Oluşturma Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faturakalem',
            name='silen_kullanici',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_silen', to=settings.AUTH_USER_MODEL, verbose_name='Silen Kullanıcı'),
        ),
        migrations.AddField(
            model_name='faturakalem',
            name='silindi',
            field=models.BooleanField(default=False, verbose_name='Silindi'),
        ),
        migrations.AddField(
            model_name='faturakalem',
            name='silinme_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi'),
        ),
        migrations.AddField(
            model_name='kasa',
            name='guncelleme_tarihi',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AddField(
            model_name='kasa',
            name='olusturma_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 12, 11, 13, 17, 389167, tzinfo=datetime.timezone.utc), verbose_name='Oluşturma Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kasa',
            name='silen_kullanici',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_silen', to=settings.AUTH_USER_MODEL, verbose_name='Silen Kullanıcı'),
        ),
        migrations.AddField(
            model_name='kasa',
            name='silindi',
            field=models.BooleanField(default=False, verbose_name='Silindi'),
        ),
        migrations.AddField(
            model_name='kasa',
            name='silinme_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi'),
        ),
        migrations.AddField(
            model_name='kasahareket',
            name='guncelleme_tarihi',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AddField(
            model_name='kasahareket',
            name='silen_kullanici',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_silen', to=settings.AUTH_USER_MODEL, verbose_name='Silen Kullanıcı'),
        ),
        migrations.AddField(
            model_name='kasahareket',
            name='silindi',
            field=models.BooleanField(default=False, verbose_name='Silindi'),
        ),
        migrations.AddField(
            model_name='kasahareket',
            name='silinme_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi'),
        ),
        migrations.AddField(
            model_name='stokkart',
            name='guncelleme_tarihi',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AddField(
            model_name='stokkart',
            name='silen_kullanici',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_silen', to=settings.AUTH_USER_MODEL, verbose_name='Silen Kullanıcı'),
        ),
        migrations.AddField(
            model_name='stokkart',
            name='silindi',
            field=models.BooleanField(default=False, verbose_name='Silindi'),
        ),
        migrations.AddField(
            model_name='stokkart',
            name='silinme_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi'),
        ),
    ]
