# Generated by Django 5.2.4 on 2025-07-14 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0009_carihareket_doviz_kuru_carihareket_tl_karsiligi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banka',
            name='bakiye',
        ),
        migrations.RemoveField(
            model_name='carikart',
            name='bakiye',
        ),
        migrations.RemoveField(
            model_name='kasa',
            name='bakiye',
        ),
    ]
