# Generated by Django 5.2.4 on 2025-07-21 10:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0010_remove_banka_bakiye_remove_carikart_bakiye_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stokkart',
            name='para_birimi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stoklar', to='muhasebe.parabirimi', verbose_name='Para Birimi'),
        ),
        migrations.AlterField(
            model_name='carihareket',
            name='islem_tipi',
            field=models.CharField(choices=[('nakit', 'Nakit'), ('banka', 'Banka'), ('pos', 'POS'), ('virman', 'Virman'), ('diger', 'Diğer')], max_length=10, verbose_name='İşlem Tipi'),
        ),
        migrations.AlterField(
            model_name='stokkart',
            name='kod',
            field=models.CharField(editable=False, max_length=30, unique=True, verbose_name='Stok Kodu'),
        ),
        migrations.CreateModel(
            name='StokSecenek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('silindi', models.BooleanField(default=False, verbose_name='Silindi')),
                ('silinme_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('baslik', models.CharField(max_length=100, verbose_name='Seçenek Başlığı')),
                ('sira', models.IntegerField(default=0, verbose_name='Sıra')),
                ('silen_kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_silen', to=settings.AUTH_USER_MODEL, verbose_name='Silen Kullanıcı')),
                ('stok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secenekler', to='muhasebe.stokkart')),
            ],
            options={
                'verbose_name': 'Stok Seçeneği',
                'verbose_name_plural': 'Stok Seçenekleri',
                'db_table': 'stok_secenekler',
                'ordering': ['sira', 'baslik'],
            },
        ),
        migrations.CreateModel(
            name='StokSecenekDeger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('silindi', models.BooleanField(default=False, verbose_name='Silindi')),
                ('silinme_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('deger', models.CharField(max_length=100, verbose_name='Değer')),
                ('fiyat_tipi', models.CharField(choices=[('sabit', 'Sabit Tutar'), ('yuzde', 'Yüzde')], default='sabit', max_length=10, verbose_name='Fiyat Tipi')),
                ('fiyat_degeri', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Fiyat Değeri')),
                ('sira', models.IntegerField(default=0, verbose_name='Sıra')),
                ('secenek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degerler', to='muhasebe.stoksecenek')),
                ('silen_kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_silen', to=settings.AUTH_USER_MODEL, verbose_name='Silen Kullanıcı')),
            ],
            options={
                'verbose_name': 'Seçenek Değeri',
                'verbose_name_plural': 'Seçenek Değerleri',
                'db_table': 'stok_secenek_degerleri',
                'ordering': ['sira', 'deger'],
            },
        ),
        migrations.CreateModel(
            name='StokGrupFiyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('silindi', models.BooleanField(default=False, verbose_name='Silindi')),
                ('silinme_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('satis_fiyati', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Özel Satış Fiyatı')),
                ('cari_grup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stok_fiyatlari', to='muhasebe.carigrup')),
                ('silen_kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_silen', to=settings.AUTH_USER_MODEL, verbose_name='Silen Kullanıcı')),
                ('stok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grup_fiyatlari', to='muhasebe.stokkart')),
            ],
            options={
                'verbose_name': 'Stok Grup Fiyatı',
                'verbose_name_plural': 'Stok Grup Fiyatları',
                'db_table': 'stok_grup_fiyatlari',
                'unique_together': {('stok', 'cari_grup')},
            },
        ),
    ]
