# Generated by Django 5.2.4 on 2025-07-22 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0012_stoksecenekdeger_varsayilan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenelStokSecenek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('silindi', models.BooleanField(default=False, verbose_name='Silindi')),
                ('silinme_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('baslik', models.CharField(max_length=100, unique=True, verbose_name='Seçenek Başlığı')),
                ('sira', models.IntegerField(default=0, verbose_name='Sıra')),
                ('silen_kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_silen', to=settings.AUTH_USER_MODEL, verbose_name='Silen Kullanıcı')),
            ],
            options={
                'verbose_name': 'Genel Stok Seçeneği',
                'verbose_name_plural': 'Genel Stok Seçenekleri',
                'db_table': 'genel_stok_secenekler',
                'ordering': ['sira', 'baslik'],
            },
        ),
        migrations.CreateModel(
            name='GenelStokSecenekDeger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('silindi', models.BooleanField(default=False, verbose_name='Silindi')),
                ('silinme_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('deger', models.CharField(max_length=100, verbose_name='Değer')),
                ('fiyat_tipi', models.CharField(choices=[('sabit', 'Sabit Tutar'), ('yuzde', 'Yüzde')], default='sabit', max_length=10, verbose_name='Fiyat Tipi')),
                ('fiyat_degeri', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Fiyat Değeri')),
                ('sira', models.IntegerField(default=0, verbose_name='Sıra')),
                ('varsayilan', models.BooleanField(default=False, verbose_name='Varsayılan')),
                ('secenek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degerler', to='muhasebe.genelstoksecenek')),
                ('silen_kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_silen', to=settings.AUTH_USER_MODEL, verbose_name='Silen Kullanıcı')),
            ],
            options={
                'verbose_name': 'Genel Seçenek Değeri',
                'verbose_name_plural': 'Genel Seçenek Değerleri',
                'db_table': 'genel_stok_secenek_degerleri',
                'ordering': ['sira', 'deger'],
            },
        ),
    ]
